### ISSUE TITLE
API: getEvents

### ISSUE THREAD

**Issue by Sean-OCallaghan** [UCMercedACM/Chapter-Website#136]
# Feature Request

---

## Describe the requirements of the solution
This is an API that will be able to generate JSON data for all events listed on ACM's Catlife.

EXAMPLE JSON FOR EACH EVENT

{
Title:
Description:
date:
attendanceCode:
}

JavaScript
Firebase
Webscraping
API
Talk to Sean for access in CatLife

**Comment by No767** [comment]
So, as of now, *technically* we never post anything on Catlife. Most if not all, are scheduled on Discord and Notion rather than Catlife (as literally no one checks it). In addition, this feature has been implemented in https://github.com/UCMercedACM/kanae/pull/27, so that's done.
