### ISSUE TITLE
feature/AddEventsToFirebase

### ISSUE THREAD

**Issue by Sean-OCallaghan** [UCMercedACM/Chapter-Website#141]
# Feature Request

---

## Please describe what aspect of the project are you addressing
Using the API from the presence that receives the events, add them to firebase and give them a doc ID of the apiID.
Here is what the data should have:
{
title: string
type: string
description: string
location: string
time: date object 
pastEvent: boolean
attendance: code
}

When the function is ran, we need to add every event to our firebase database if it does not already exist. we can check this with the apiID of the event given by the API from presence. We also need to generate a 6 DIGIT attendance code for each event that is unique, you must check that it doesn't already exist when in the Database. 

Generate a code for this

**Comment by No767** [comment]
Along with the short uuid/twitter(x) snowflake implementations within Kanae, most if not all of this feature is entirely complete finished on the backend. All that needs to be done is to pull the data from the backend, and display it.
